### ISSUE TITLE
[tbendfelt on 2016-02-24 11:21:13] : syncgps read does not validate the seconds field in GPS timestring

### ISSUE THREAD

**Issue by dglo** [dglo/dor-driver#101]
dh_syncgps_read_proc() takes care to validate the timestring sourced from the master clock PPS. For some reason it only implemented a check on day, hour and minute ... allowing a corrupted seconds field to pass. 

Example:

Driver catches corrupted non-second fields:

Feb 24 01:01:43 scube kernel: Bad time string character 0xb0 at position 1; retrying.
Feb 24 01:01:45 scube kernel: Bad time string character 0x00 at position 8; retrying.
Feb 24 01:01:45 scube kernel: dh_syncgps_read_proc: Skipping non-SOH start byte (0x00) on card 3.
Feb 24 01:01:45 scube kernel: dh_syncgps_read_proc: Skipping non-SOH start byte (0x00) on card 3.
Feb 24 01:01:45 scube kernel: dh_syncgps_read_proc: Skipping non-SOH start byte (0x44) on card 3.
Feb 24 01:01:45 scube kernel: dh_syncgps_read_proc: Skipping non-SOH start byte (0x92) on card 3.
Feb 24 01:01:45 scube kernel: dh_syncgps_read_proc: Skipping non-SOH start byte (0x6e) on card 3.
Feb 24 01:01:45 scube kernel: dh_syncgps_read_proc: Skipping non-SOH start byte (0xa1) on card 3.
Feb 24 01:01:45 scube kernel: dh_syncgps_read_proc: Skipping non-SOH start byte (0x86) on card 3.

But delivers a string with corrupted seconds field:

15990176 [2016-02-24 01:28:49,110] [Thread-0] WARN  icecube.daq.dor.GPSInfo  - Failed to parse GPS timestring 055:01:28:?^A
15990177 [2016-02-24 01:28:49,111] [Thread-0] WARN  icecube.daq.time.gps.DSBGPSService  - Got GPS exception - time translation to UTC will be incomplete
icecube.daq.dor.GPSException: Malformed record from "/proc/driver/domhub/card3/syncgps"
        at icecube.daq.dor.Driver.readGPS(Driver.java:293)
        at icecube.daq.time.gps.DSBGPSService$GPSCollector.run(DSBGPSService.java:285)
Caused by: java.lang.NumberFormatException: For input string: "?^A"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:492)
        at java.lang.Integer.parseInt(Integer.java:527)
        at icecube.daq.dor.GPSInfo.<init>(GPSInfo.java:31)
        at icecube.daq.dor.Driver.readGPS(Driver.java:285)
        ... 1 more

Additional Information: dh_syncgps_read_proc()
<snip>>>
 tbuf[0] = cts;
        int i;
        int goodstring = 1;
        for(i=1; i<DH_TSBYTES; i++) {
            cts = (unsigned char) (dh_read_regi(icard, DH_RG_TSTRG) & 0xFF);
            vvprintk(KERN_INFO "dh_syncgps_read_proc: card %d read byte 0x%02x\n", icard, (unsigned char) cts);
            /* Check for valid digits - should probably write a real parser */
            if((( i >= 1 && i <= 3) || /* Day */
                ( i == 5 || i == 6) || /* Hr */
                ( i == 8 || i == 9))          <--------------------What about the seconds?
               && /* Enforce 0..9 */
               (cts < '0' || cts > '9')) {
                goodstring = 0; break;
            } else if((i == 4 || i == 7 || i == 10) && cts != ':') {
                goodstring = 0; break;
            }
            tbuf[i] = cts;
        }
        if(!goodstring) {
            printk(KERN_WARNING "Bad time string character 0x%02x at position %d; retrying.\n",
                   cts, i);
            continue;
        }
<<<snip>

**Comment by dglo** [comment]
[jkelley on 2016-03-15 03:14:12]
Add seconds bytes to validation check.

**Comment by dglo** [comment]
[jkelley on 2017-01-31 13:49:26]
V02-14-06

**Comment by dglo** [comment]
No associated GitHub commit
