### ISSUE TITLE
[jkelley on 2017-05-22 16:22:05] : pDAQ reports device file "not found" for dropped DOMs

### ISSUE THREAD

**Issue by dglo** [dglo/dor-driver#118]
No associated GitHub commit

**Comment by dglo** [comment]
[tbendfelt on 2017-05-22 16:31:23]
This is what is reported to StringHub:

CnCServer icecube.daq.domapp.dataacquisition.DataAcquisition-23A WARN [2017-05-10 01:18:19.7400000000] DOM [23A] c22b0237db9b is not responding to DOMApp query -  will attempt to softboot
java.io.FileNotFoundException: /dev/dhc2w3dA (Resource temporarily unavailable)
    at java.io.RandomAccessFile.open0(Native Method)
    at java.io.RandomAccessFile.open(RandomAccessFile.java:316)
    at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243)
    at icecube.daq.domapp.DOMIO.<init>(DOMIO.java:28)
    at icecube.daq.domapp.DOMApp.<init>(DOMApp.java:35)
    at icecube.daq.domapp.dataacquisition.DataAcquisition.doInitialization(DataAcquisition.java:659)
    at icecube.daq.domapp.DataCollector.launch_runcore(DataCollector.java:349)
    at icecube.daq.domapp.DataCollector.run(DataCollector.java:314)
CnCServer icecube.daq.domapp.dataacquisition.DataAcquisition-23B WARN [2017-05-10 01:18:19.7400000000] DOM [23B] 86fe012ee332 is not responding to DOMApp query -  will attempt to softboot
java.io.FileNotFoundException: /dev/dhc2w3dB (Resource temporarily unavailable)
    at java.io.RandomAccessFile.open0(Native Method)
    at java.io.RandomAccessFile.open(RandomAccessFile.java:316)
    at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243)
    at icecube.daq.domapp.DOMIO.<init>(DOMIO.java:28)
    at icecube.daq.domapp.DOMApp.<init>(DOMApp.java:35)
    at icecube.daq.domapp.dataacquisition.DataAcquisition.doInitialization(DataAcquisition.java:659)
    at icecube.daq.domapp.DataCollector.launch_runcore(DataCollector.java:349)
    at icecube.daq.domapp.DataCollector.run(DataCollector.java:314)
CnCServer icecube.daq.domapp.dataacquisition.DataAcquisition-23A WARN [2017-05-10 01:18:23.7620000000] Softboot attempt of [23A] 000000000000 failed - retrying after 5 sec
CnCServer icecube.daq.domapp.dataacquisition.DataAcquisition-23A WARN [2017-05-10 01:18:32.8100000000] Softboot attempt of [23A] 000000000000 failed - retrying after 5 sec
CnCServer icecube.daq.domapp.dataacquisition.DataAcquisition-23B ERROR [2017-05-10 01:18:55.0200000000] Trial 0: Open of 23B failed! - comstats:
/dev/dhc2w3dB
RX: 23356224190B, MSGS=14162879 NINQ=0 PKTS=50483136 ACKS=2483569
    BADPKT=280 BADHDR=0 BADSEQ=1 NCTRL=0 NCI=50 NIC=56
TX: 19875042B, MSGS=2483569 NOUTQ=0 RESENT=0 PKTS=50483134 ACKS=47999565
    NACKQ=0 NRETXB=0 RETXB_BYTES=0 NRETXQ=0 NCTRL=0 NCI=500 NIC=159
    NCONNECTS=0 NHDWRTIMEOUTS=0 OPEN=FALSE CONNECTED=FALSE
    RXFIFO=empty TXFIFO=almost empty,empty DOM_RXFIFO=notfull
FPGA registers:
FPGA registers:
CTRL  0x6800700f
GSTAT 0x00002dc2
DSTAT 0x000000ff
TTSIC 0x0000ffff
RTSIC 0xff0000ff
INTEN 0x00010200
DOMS  0xff0000ff
MRAR  0x00093400
MRTC  0x07000000
MWAR  0x00093004
MWTC  0x07000000
CURL  0xe19e8c14
DCUR  0x3c6930ae
FLASH 0xff2e0314
DOMC  0x00000000
CERR  0x70080000
DCREV 0x00000024
FREV  0x09010471

**Comment by dglo** [comment]
[jkelley on 2018-02-13 22:14:46]
I believe this is expected behavior if the device is indeed unavailable (for example, if it's been powered off).  It looks like "FileNotFoundException" is reported even for generic errors on RandomAccessFile.open().
